### ISSUE TITLE
Cast support

### ISSUE THREAD

**Issue by mpusch88** [Bluscream/mytube#15]
If it is possible, it would be an awesome feature to support casting to myTube from another device via network, plus the ability to generate a linkable TV Code to connect to mobile youtube applications. As youtube vanced supports this, it seems like there should be a way to do this (although im unsure if vanced is just a modified youtube apk with deeper access to their api).

**Comment by Bluscream** [comment]
Duplicate of #7. If you got something to add please do it there, thank you :)
