### ISSUE TITLE
apı error

### ISSUE THREAD

**Issue by senolfndk** [Bluscream/mytube#18]
🙁 ![Ekran görüntüsü 2022-04-26 211922](https://user-images.githubusercontent.com/52818836/165366981-ad536f9f-2687-4142-9da4-83db164ee9e9.png)

**Comment by Bluscream** [comment]
From https://discord.com/channels/473391901429596170/473392366321926145/968632814713077781

> Hello everyone. It seems that there's a problem with the YouTube API right now affecting everyone without their own API key to not be able to use mytube. Luckily the solution is rather easy - use your own API key!

**Comment by senolfndk** [comment]
I created api key but it wants client id and client id secret

Windows için Posta<https://go.microsoft.com/fwlink/?LinkId=550986> ile gönderildi

Kimden: ***@***.***>
Gönderilme: 27 Nisan 2022 Çarşamba 09:51
Kime: ***@***.***>
Bilgi: şenol ***@***.***>; ***@***.***>
Konu: Re: [Ryken100/mytube] apı error (Issue #18)


From https://discord.com/channels/473391901429596170/473392366321926145/968632814713077781

Hello everyone. It seems that there's a problem with the YouTube API right now affecting everyone without their own API key to not be able to use mytube. Luckily the solution is rather easy - use your own API key!

**Comment by senolfndk** [comment]
ok
