### ISSUE TITLE
myTube app

### ISSUE THREAD

**Issue by Andrey6777** [Bluscream/mytube#22]
W10M
myTube!: 4.0.21.0
Beta: yes

**Description:**
Video is not playing (eternal loading). And it crashes when I try to add an account.
The problem is both with the standard API and with your own.

Fix it, it's the last hope.

**Comment by senolfndk** [comment]
> W10M myTube!: 4.0.21.0 Beta: evet
> 
> **Açıklama:** Video oynatılmıyor (sürekli yükleniyor). Ve bir hesap eklemeye çalıştığımda çöküyor. Sorun hem standart API'de hem de kendi API'nizde.
> 
> Düzelt, bu son umut.
same problem

**Comment by Bluscream** [comment]
myTube is no longer being maintained, sorry. Use the normal youtube app or something like https://invidious.io instead

**Comment by mediaexplorer74** [comment]
> myTube is no longer being maintained, sorry. Use the normal youtube app or something like https://invidious.io instead

Hi, [Bluscream](https://github.com/Bluscream).
Are you from Ryken Studio team ore not? 
If yes, please decide to made myTube open-sourced (minimum - old miniversion 2.x for WindowPhones).

Best wishes,
MediaExplorer
Cancelled W10M developer-enthusiast

**Comment by senolfndk** [comment]
> > myTube'un bakımı artık yapılmıyor, üzgünüm. Bunun yerine normal youtube uygulamasını veya [https://invidious.io gibi bir şeyi kullanın](https://invidious.io)
> 
> Merhaba [Bluscream](https://github.com/Bluscream) . Ryken Studio ekibinden misiniz yoksa değil misiniz? Cevabınız evet ise, lütfen myTube'u açık kaynak yapmaya karar verin (minimum - WindowPhones için eski mini sürüm 2.x).
> 
> En iyi dileklerimle, MediaExplorer W10M geliştirici meraklısını İptal Etti

https://discord.com/channels/473391901429596170/473392023517396994

**Comment by Bluscream** [comment]
> Hi, [Bluscream](https://github.com/Bluscream). Are you from Ryken Studio team ore not?

I am not, i have just helped Ryken set up this github repo and provided feedback while the project was still active.

**Comment by mediaexplorer74** [comment]
> > Hi, [Bluscream](https://github.com/Bluscream). Are you from Ryken Studio team ore not?
> 
> I am not, i have just helped Ryken set up this github repo and provided feedback while the project was still active.

Ok. Sorry for (to) disturbing you

**Comment by Proxima0** [comment]
> myTube больше не поддерживается, извините. Вместо этого используйте обычн

Did I understand correctly that the project is closed? I have a myTube license purchased, but I haven't been able to log into my account for a long time. I wrote to rykenproductions@outlook.com but no one responded. Help me.
![3](https://github.com/Ryken100/mytube/assets/4592768/70949b9a-219c-4f4d-b68c-ef93f9b90347)

**Comment by Bluscream** [comment]
Nevermind what i previously said. It's all working! You just need to set your own API key

![](https://i.imgur.com/LryupIV.png)
![](https://i.imgur.com/Jznh3eN.png)

**Comment by mediaexplorer74** [comment]
> Nevermind what i previously said. It's all working! You just need to set your own API key
> 
[Bluscream](https://github.com/Bluscream) , cool solving! :) 
Yea, it's all working even on my old sweet Windowsphone Lumia 950 when I registered and set personal API key.
Thank you, and Merry Christamas / Happy New Year !

**Comment by Proxima0** [comment]
> Reference

Which key should I choose?
![2023-12-30_202120](https://github.com/Ryken100/mytube/assets/4592768/8ee236ba-4eac-41bf-89a0-2a19e7fb33a5)

**Comment by Proxima0** [comment]
> Неважно, что я сказал ранее. Все работает! Вам просто нужно установить свой собственный ключ API
> 
> ![](https://camo.githubusercontent.com/bb6a7507d6e6b93060de965d71c4472030206338ee50e7889abd8969b1224c0f/68747470733a2f2f692e696d6775722e636f6d2f4c7279757049562e706e67) ![](https://camo.githubusercontent.com/4c3191d9c65ccddf0ba7f61966c00348dbf3919d6a843c6f0cb975464ea201ea/68747470733a2f2f692e696d6775722e636f6d2f4a7a6e6833654e2e706e67)

Give me instructions (video) on how to do this correctly, please...

**Comment by Bluscream** [comment]
> > Reference
> 
> Which key should I choose?
> 

Data

**Comment by Bluscream** [comment]
> > Неважно, что я сказал ранее. Все работает! Вам просто нужно установить свой собственный ключ API
> >  
> Give me instructions (video) on how to do this correctly, please...

Search for "how to create youtube api key" on youtube

**Comment by Proxima0** [comment]
> > > Неважно, что я сказал ранее. Все работает! Вам просто нужно установить свой собственный ключ API
> > 
> > 
> > Give me instructions (video) on how to do this correctly, please...
> 
> Search for "how to create youtube api key" on youtube

I did it according to the instructions. It worked the second time... :)
Hurray!
